@echo off
cd /d "%~dp0sistema"
set URURAU_MONITOR_MODO_CMS=rascunho
set URURAU_PUBLICAR_DIRETO=0
set URURAU_CMS_PUBLICACAO_DIRETA=0
set SCORE_MIN_MONITOR=35
set URURAU_MONITOR_SCORE_MINIMO=35
set URURAU_SCORE_MINIMO_RASCUNHO=35
set URURAU_MONITOR_USAR_FILA_PAINEL=1
set URURAU_V111_GNEWS_INTEGRADO=0
set URURAU_V111_USAR_CICLO_COMBINADO=0
set URURAU_V111_USAR_EXTRACAO_COMPLETA=0
set URURAU_V110_MONITOR_GNEWS_LEGADO=0
set URURAU_V108_GNEWS_TERMOS=0
set URURAU_SOURCE_HUNTER_ATIVO=0
set URURAU_GNEWS_DESLIGADO_NO_MONITOR=1
set URURAU_AUTOFONTES_V131_ATIVO=1
set URURAU_AUTO_DIAGNOSTICO_FONTE=1
python ururau_monitor.py --modo-cms rascunho
pause

