@echo off
cd /d "%~dp0sistema"
set URURAU_MONITOR_MODO_CMS=rascunho
set URURAU_PUBLICAR_DIRETO=0
set URURAU_CMS_PUBLICACAO_DIRETA=0
set URURAU_MONITOR_RASCUNHO_SE_NAO_APROVAR=1
set SCORE_MIN_MONITOR=35
set URURAU_SCORE_MINIMO_RASCUNHO=35
set URURAU_MIN_CHARS_FONTE_MONITOR=350
set URURAU_V111_SCORE_MINIMO_PAUTA=35
set URURAU_V111_GNEWS_MAX_RESULTADOS_POR_TERMO=6
set URURAU_V111_GNEWS_JANELA_HORAS=12
set URURAU_V111_GNEWS_INTEGRADO=1
set URURAU_V110_MONITOR_GNEWS_LEGADO=1
set URURAU_SOURCE_HUNTER_ATIVO=1
set URURAU_AUTOFONTES_V131_ATIVO=1
python ururau_monitor.py --modo-cms rascunho --ciclo-unico --intervalo 120 --max-hora 24
pause
