# fix_neural_service.ps1
$base = "C:\Users\fabri\Downloads\PURAL_EDITORIAL_V47_12_PREMIUM_OPERACIONAL\PURAL_EDITORIAL_V47_12_PREMIUM_OPERACIONAL"

$fix_b64 = "IyAtKi0gY29kaW5nOiB1dGYtOCAtKi0KIiIiCkZpeCBuZXVyYWxfc2VydmljZS5weSDigJQgY29ycmlnZSBub21lcyBkZSBtw6l0b2Rvcy4KIiIiCmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aAoKYmFzZSA9IFBhdGgociJDOlxVc2Vyc1xmYWJyaVxEb3dubG9hZHNcUFVSQUxfRURJVE9SSUFMX1Y0N18xMl9QUkVNSVVNX09QRVJBQ0lPTkFMXFBVUkFMX0VESVRPUklBTF9WNDdfMTJfUFJFTUlVTV9PUEVSQUNJT05BTCIpCnBhdGggPSBiYXNlIC8gInNpc3RlbWEiIC8gIm5ldXJhbF9zZXJ2aWNlLnB5IgoKY29kZSA9IHBhdGgucmVhZF90ZXh0KGVuY29kaW5nPSJ1dGYtOCIpCgojIENvcnJpZ2lyIG5vbWVzIGRlIG3DqXRvZG9zCmNvZGUgPSBjb2RlLnJlcGxhY2UoInNlbGYuc2NvcmVfYWRhcHRpdmUuZ2V0KCkiLCAic2VsZi5zY29yZV9hZGFwdGl2ZS5nZXRfdGhyZXNob2xkKCkiKQpjb2RlID0gY29kZS5yZXBsYWNlKCJzZWxmLmludGVydmFsb19vcHQuZ2V0KCkiLCAic2VsZi5pbnRlcnZhbG9fb3B0LmdldF9pbnRlcnZhbG8oKSIpCgpwYXRoLndyaXRlX3RleHQoY29kZSwgZW5jb2Rpbmc9InV0Zi04IikKcHJpbnQoIltPS10gbmV1cmFsX3NlcnZpY2UucHkgY29ycmlnaWRvIikKcHJpbnQoIiAgc2NvcmVfYWRhcHRpdmUuZ2V0KCkg4oaSIGdldF90aHJlc2hvbGQoKSIpCnByaW50KCIgIGludGVydmFsb19vcHQuZ2V0KCkg4oaSIGdldF9pbnRlcnZhbG8oKSIpCg=="
$bytes = [System.Convert]::FromBase64String($fix_b64)
[System.IO.File]::WriteAllBytes("$base\sistema\_fix_neural.py", $bytes)

Write-Host "[INFO] Corrigindo neural_service.py..." -ForegroundColor Yellow
python "$base\sistema\_fix_neural.py"

Remove-Item "$base\sistema\_fix_neural.py" -ErrorAction SilentlyContinue

Write-Host "CONCLUIDO. Rode agora: .\49_INICIAR_NEURAL.bat" -ForegroundColor Cyan
